.TH treedude 6 2022-06-18

.SH NAME
\fBtreedude\fR \- a clone of the mini-game from Superhot

.SH SYNOPSIS
\fBtreedude [\fB\-nvV\fR]

.SH DESCRIPTION
\fBtreedude\fR is a clone of the mini-game from Superhot titled 'Tree Dude Tree Dude Dude'. Chop as much of the tree as you can while avoiding branches and keeping an eye on the timer.

Written in C89/90 with the Curses library, complies with \fISUSv2\fR.

.SH CONTROLS
.TP
.B LeftArrow, A, H
Chop left
.TP
.B RightArrow, D, L
Chop right
.TP
.B Enter
Continue
.TP
.B Q, Esc
Quit

.SH OPTIONS
.TP
.B n
Do not read or write the high score from the \fB$XDG_DATA_HOME\fR directory.
.TP
.B v, V
Print \fBtreedude\fR version and exit.

.SH ENVIRONMENT
.TP
.B XDG_CONFIG_HOME
The user's high score is located within the directory defined. Uses \f(BI$HOME\fI/.config\fR if not defined in compliance with the \fIXDG Base Directory Specification\fR.

.SH FILES
.TP
.I \f(BI$XDG_DATA_HOME\fI/treedude/score\fR
User's high score.

.SH STANDARDS
.TP
Single UNIX Specification, Version 2 (SUSv2)
Includes \fIC89/90\fR, \fIPOSIX.1-1990\fR, \fIPOSIX.2-1992\fR, \fIPOSIX.1b-1993\fR, \fIPOSIX.1c-1995\fR.
.TP
XDG Base Directory Specification

.SH BUGS
Bugs and issues can be reported on GitHub or GitLab.
.TP
<https://github.com/n-ivkovic/treedude/issues>
.TP
<https://gitlab.com/n-ivkovic/treedude/issues>

.SH AUTHORS
Nicholas Ivkovic <https://nivkovic.net>.

.SH COPYRIGHT
Copyright (c) 2022 Nicholas Ivkovic.

Licensed under the GNU General Public License version 3 or later. See ./LICENSE, or <https://gnu.org/licenses/gpl.html> if more recent, for details.

This is free software: you are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law.
